version: '3'

networks: 
  internal:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8090:80" # LOCAL : DOCKER
    volumes:
      - ./src:/var/www/html # LOCAL : DOCKER
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - internal

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true # Enables a shell like interface if we need to interact with the container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - internal

  php: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports: 
      - "9000:9000"
    networks: 
      - internal

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html 
    networks: 
      - internal

  npm:
    image: node:latest
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks: 
      - internal